name = "questa-r2-api"
main = "cloudflare-worker.js"
compatibility_date = "2023-12-07"

# R2バケット設定
[[r2_buckets]]
binding = "QUESTA_BUCKET"
bucket_name = "questa"

# D1データベース設定
[[d1_databases]]
binding = "TESTAPP_DB"
database_name = "testapp-database"
database_id = "your-database-id-here"

# 環境変数
[vars]
ADMIN_TOKEN = "questa-admin-2024"
JWT_SECRET = "your-jwt-secret-here"

# カスタムドメイン設定（オプション）
# [env.production]
# routes = [
#   { pattern = "api.allfrom0.top/api/*", zone_name = "allfrom0.top" }
# ]