name = "data-manager"
compatibility_date = "2024-09-14"

[assets]
directory = "."
exclude = ["wrangler.toml", "package.json", "next.config.js", "pages/", "node_modules/", ".git/", ".gitignore"]

# Static site configuration
[[routes]]
pattern = "*"
custom_origin = true