name = "testapp-auth"
main = "workers/auth.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "testapp-database"
database_id = "ae1bafef-5bf9-4a9d-9773-14c2b017d2be"

[[kv_namespaces]]
binding = "SESSIONS"
id = "496281ad0a90470aa04a5338a4681f7b"